# -*- coding: utf-8 -*-
import csv
import random

# We define the raw dataset: (id, Question, Correct Answer, Distractors)
RAW_DATA = [
    (1, "In which place Lord Buddha has been enlightened?", "Bodhgaya", ["Sarnath", "Lumbini", "Kushinagar"]),
    (2, 'Who is the founder of "Arya Samaj"?', "Swami Dayanand", ["Swami Vivekananda", "Raja Rammohan Roy", "Ramakrishna Paramahansa"]),
    (3, 'What is the sign language of "Punjabi"?', "Gurmukhi", ["Devanagari", "Shahmukhi", "Bengali"]),
    (4, "What is the Southern Most area of Indian land?", "Kanyakumari", ["Indira Point", "Indira Col", "Kavaratti"]),
    (5, "The sun rises in which state of India firstly?", "Arunachal Pradesh", ["Assam", "Manipur", "Nagaland"]),
    (6, "Insulin used to cure which disease?", "Diabetes", ["Cancer", "Malaria", "Tuberculosis"]),
    (7, '"Bihu" is a famous festival of which state?', "Assam", ["West Bengal", "Odisha", "Sikkim"]),
    (8, "What vitamin is found in 'Gooseberry'?", "Vitamin C", ["Vitamin A", "Vitamin B", "Vitamin D"]),
    (9, "Who was the first governor general of India?", "Lord William Bentinck", ["Lord Canning", "Lord Mountbatten", "Warren Hastings"]),
    (10, "In which country 'Paper' was invented?", "China", ["India", "Egypt", "Greece"]),
    (11, "'Phyllanthus Emblica' is whose scientific name?", "Gooseberry", ["Mango", "Apple", "Guava"]),
    (12, "What was the childhood name of 'Gautam Buddha'?", "Siddharth", ["Gautam", "Rahul", "Vardhamana"]),
    (13, "Who is the supreme commander of Indian Armed Forces?", "President", ["Prime Minister", "Chief of Defence Staff", "Chief Justice"]),
    (14, "Night Blindness is caused by lack of which vitamin?", "Vitamin A", ["Vitamin B", "Vitamin C", "Vitamin D"]),
    (15, '"Pongal" is a famous festival of which state?', "Tamil Nadu", ["Kerala", "Andhra Pradesh", "Karnataka"]),
    (16, "Who invented 'Television'?", "J.L. Baird", ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi"]),
    (17, "Who was the first female ruler of India?", "Razia Sultana", ["Mumtaz Mahal", "Nur Jahan", "Rani Lakshmibai"]),
    (18, "Fish takes breath by:", "Gills", ["Lungs", "Skin", "Spiracles"]),
    (19, "Who gave the slogan 'Inquilab Zindabad'?", "Hasrat Mohani", ["Bhagat Singh", "Subhas Chandra Bose", "Chandrashekhar Azad"]),
    (20, "In which date 'Jallianwala Bagh Tragedy' happened?", "13 April 1919", ["15 August 1919", "26 January 1919", "10 May 1919"]),
    (21, "After he left Congress, Subhas Chandra Bose founded which group?", "All India Forward Bloc", ["Swaraj Party", "Ghadar Party", "Indian National Army"]),
    (22, "Who is known as 'Punjab Kesari'?", "Lala Lajpat Rai", ["Bal Gangadhar Tilak", "Bipin Chandra Pal", "Bhagat Singh"]),
    (23, "'J.P. Saunders' was killed in which city?", "Lahore", ["Delhi", "Amritsar", "Karachi"]),
    (24, "Who sacrificed his life firstly in 1857 revolt?", "Mangal Pandey", ["Tantia Tope", "Bahadur Shah Zafar", "Nana Sahib"]),
    (25, "Who was the first female governor of India?", "Sarojini Naidu", ["Sucheta Kripalani", "Annie Besant", "Indira Gandhi"]),
    (26, "First female Indian, who summited Mt. Everest twice?", "Santosh Yadav", ["Bachendri Pal", "Arunima Sinha", "Premalata Agarwal"]),
    (27, "Who founded 'Brahma Samaj'?", "Raja Rammohan Rai", ["Swami Dayanand", "Debendranath Tagore", "Keshab Chandra Sen"]),
    (28, "When did Vasco da gama came into India?", "1498 AD", ["1600 AD", "1526 AD", "1757 AD"]),
    (29, "When did East India company came into India?", "1600 AD", ["1498 AD", "1602 AD", "1608 AD"]),
    (30, "Guru Nanak Dev was born in which place?", "Nankana Sahib", ["Amritsar", "Patna Sahib", "Anandpur Sahib"]),
    (31, "Who has given the concept of Khalsa?", "Guru Govind Singh", ["Guru Nanak", "Guru Arjun Dev", "Guru Tegh Bahadur"]),
    (32, "Akbar was impressed by which sikh Guru?", "Guru Ramdas", ["Guru Nanak", "Guru Arjun Dev", "Guru Angad Dev"]),
    (33, "Who is known as 'Iron Man of India'?", "Sardar Vallabh Bhai Patel", ["Jawaharlal Nehru", "Subhas Chandra Bose", "Lal Bahadur Shastri"]),
    (34, "Who wrote 'Arthashastra'?", "Kautilya", ["Megasthenes", "Kalidasa", "Banabhatta"]),
    (35, "When do we observe 'Red Cross Day'?", "8 May", ["5 June", "22 April", "10 December"]),
    (36, "'Onam' is the famous festival of which state?", "Kerala", ["Tamil Nadu", "Karnataka", "Andhra Pradesh"]),
    (37, "When did Delhi became the capital of India?", "1911 AD", ["1947 AD", "1950 AD", "1857 AD"]),
    (38, "Peacock was declared as the national bird of India in which year?", "1963", ["1950", "1972", "1947"]),
    (39, "Which planet is known as the 'Galaxy like planet'?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
    (40, "Which is the largest satellite of solar system?", "Ganymede", ["Titan", "Phobos", "Deimos"]),
    (41, "What is the Ratio of Indian National Flag?", "3:2", ["2:3", "4:3", "3:1"]),
    (42, "Who has written 'National Song'?", "Bankim Chandra Chatterjee", ["Rabindranath Tagore", "Sarojini Naidu", "Sri Aurobindo"]),
    (43, "Indian Calendar follows which pattern?", "Saka Samvat", ["Vikram Samvat", "Gregorian pattern", "Hijri pattern"]),
    (44, "Pacemaker is associated with which organ?", "Heart", ["Brain", "Kidney", "Lungs"]),
    (45, "Which of the following is known as 'Master gland'?", "Pituitary gland", ["Thyroid gland", "Adrenal gland", "Pancreas"]),
    (46, "Humans used which metal firstly?", "Copper", ["Iron", "Bronze", "Gold"]),
    (47, "Which Article is associated with 'Lok Sabha'?", "Article 81", ["Article 80", "Article 79", "Article 82"]),
    (48, "Firstly, Metro Train was started in which city of India?", "Kolkata", ["Delhi", "Mumbai", "Chennai"]),
    (49, "In which year 'Indian Railway' was established?", "1853 AD", ["1885 AD", "1905 AD", "1947 AD"]),
    (50, "Who was the first Indian Astronaut?", "Rakesh Sharma", ["Kalpana Chawla", "Sunita Williams", "Ravish Malhotra"]),
    (51, "What is headquarter of 'International Court of Justice'?", "The Hague", ["Geneva", "New York", "London"]),
    (52, "Who invented 'Rocket' in India?", "Haider Ali", ["Tipu Sultan", "Akbar", "Shivaji"]),
    (53, "Which Britisher has fought for Indian Freedom against British Empire?", "William Gordon", ["William Bentinck", "Warren Hastings", "Thomas Munro"]),
    (54, "Which country shares the land border with maximum countries?", "China", ["Russia", "India", "Canada"]),
    (55, "Which gas mainly found in 'Bio Gas'?", "Methane", ["Carbon Dioxide", "Hydrogen", "Nitrogen"]),
    (56, "Earth rotates on its axis __________.", "West to East", ["East to West", "North to South", "South to North"]),
    (57, "In which year, 'Amazon' was established?", "1994 AD", ["1998 AD", "2000 AD", "1990 AD"]),
    (58, "Which was the first Hindi language newspaper?", "Udant Martand", ["Samachar Darpan", "Bengal Gazette", "Kesari"]),
    (59, "India has won eight times Gold in which olympics game?", "Hockey", ["Cricket", "Football", "Kabaddi"]),
    (60, "Where is the hq of 'International Olympics'?", "Lausanne", ["Geneva", "Zurich", "Paris"]),
    (61, "Which organ of human body filters urea from Blood?", "Kidney", ["Liver", "Heart", "Spleen"]),
    (62, "Which of the following range is known as 'Himadri'?", "Greater Himalaya", ["Lesser Himalaya", "Outer Himalaya", "Karakoram"]),
    (63, "Which woman has firstly summited Mt. Everest in the world?", "Junko Tabei", ["Bachendri Pal", "Yoko Ono", "Tamae Watanabe"]),
    (64, "'Jaundice' is associated with which organ?", "Liver", ["Kidney", "Heart", "Lungs"]),
    (65, "In which year Microsoft was established?", "1975 AD", ["1985 AD", "1995 AD", "1970 AD"]),
    (66, "Ashoka was influenced by which Buddhist Monk?", "Upagupta", ["Chanakya", "Chandragupta", "Bindusara"]),
    (67, "Which Mughal Emperor was illiterate?", "Akbar", ["Babur", "Shah Jahan", "Humayun"]),
    (68, "Who established City 'Amritsar'?", "Guru Ramdas", ["Guru Nanak", "Guru Arjun Dev", "Guru Tegh Bahadur"]),
    (69, "Firstly, who told that Earth rotates around the sun?", "Copernicus", ["Galileo", "Kepler", "Newton"]),
    (70, "Who established 'Charminar' in Hyderabad?", "Quli Qutub Shah", ["Ibrahim Qutb Shah", "Muhammad Qutb Shah", "Hayat Bakshi Begum"]),
    (71, "When do we observe 'Sports Day'?", "29th August", ["15th August", "29th July", "21st June"]),
    (72, "Family Culicidae is the scientific name of whom?", "Mosquito", ["Housefly", "Honeybee", "Butterfly"]),
    (73, "Who is known as Napoleon of India?", "Samudragupta", ["Chandragupta Maurya", "Ashoka", "Harsha"]),
    (74, "What is the shortcut key to insert a hyperlink in MS office?", "Ctrl + K", ["Ctrl + H", "Ctrl + L", "Ctrl + M"]),
    (75, "In which year Mahatma Gandhi was born?", "1869", ["1875", "1857", "1885"]),
    (76, "Who is the author of 'My Experiment with Truth'?", "Mahatma Gandhi", ["Jawaharlal Nehru", "B.G. Tilak", "Subhas Chandra Bose"]),
    (77, "Dada Saheb Phalke award is associate with which field?", "Film", ["Sports", "Literature", "Science"]),
    (78, "Which is the highest bravery award in India?", "Paramveer Chakra", ["Bharat Ratna", "Ashok Chakra", "Vir Chakra"]),
    (79, "Who is known as the Shakespeare of India?", "Kalidas", ["Rabindranath Tagore", "Tulsidas", "Valmiki"]),
    (80, "First Indian satellite was launched in which year?", "1975", ["1969", "1980", "1983"]),
    (81, "In which date we celebrate 'International Women's Day'?", "8 March", ["10 December", "5 June", "22 April"]),
    (82, "Who established 'Banaras Hindu University'?", "Madan Mohan Malviya", ["Raja Rammohan Roy", "Swami Vivekananda", "Mahatma Gandhi"]),
    (83, "What is the total length of Indian Coastal line?", "7516 km", ["6100 km", "8200 km", "5400 km"]),
    (84, "Who built G.T Road?", "Sher Shah Suri", ["Akbar", "Alauddin Khilji", "Chandragupta Maurya"]),
    (85, "'Impaired Blood clotting' is caused by the lack of which vitamin?", "Vitamin K", ["Vitamin C", "Vitamin D", "Vitamin E"]),
    (86, "'Human Infertility' is caused by the lack of which vitamin?", "Vitamin E", ["Vitamin A", "Vitamin B", "Vitamin C"]),
    (87, "'Calciferol' is the scientific name of which vitamin?", "Vitamin D", ["Vitamin A", "Vitamin B", "Vitamin C"]),
    (88, "We observe 'National Science Day' on which date?", "28 February", ["28 January", "28 March", "28 April"]),
    (89, "Red Blood cells made in which part of the body?", "Bone Marrow", ["Liver", "Spleen", "Kidney"]),
    (90, "In Eye Donation, which part of eye is suppose to donate?", "Cornea", ["Retina", "Lens", "Iris"]),
    (91, "Congress was divided into two parts in which year?", "1907", ["1905", "1911", "1916"]),
    (92, "In which year FIFA was established?", "1904", ["1910", "1896", "1920"]),
    (93, "Which country is the highest producer of Silver?", "Mexico", ["China", "Peru", "Australia"]),
    (94, "We observe 'world Earth Day' on which date?", "22 April", ["22 March", "22 May", "22 June"]),
    (95, "'Flower Valley' is situated in which state?", "Uttarakhand", ["Himachal Pradesh", "Sikkim", "Jammu & Kashmir"]),
    (96, "Hopman cup is associated with which sports?", "Tennis", ["Badminton", "Squash", "Table Tennis"]),
    (97, "What is the life span of RBC?", "120 Days", ["60 Days", "90 Days", "150 Days"]),
    (98, "Who is the developer of 'C program language'?", "Dennis Ritchie", ["Ken Thompson", "Bjarne Stroustrup", "Linus Torvalds"]),
    (99, "UNESCO gives 'Kalinga Award' in which field?", "Science", ["Literature", "Peace", "Journalism"]),
    (100, "In which year 'Youtube' was established?", "2005", ["2004", "2006", "2008"]),
    (101, "When was 'charminar' established in Hyderabad?", "1591 AD", ["1600 AD", "1605 AD", "1556 AD"]),
    (102, "'White Revolution' is associated with which thing?", "Milk", ["Eggs", "Fish", "Petroleum"]),
    (103, "In which year firstly, national emergency was imposed in India?", "1962", ["1971", "1975", "1950"]),
    (104, "Which article is associated with Prime Minister?", "Article 74", ["Article 52", "Article 324", "Article 280"]),
    (105, "Which city is known as 'Brass city'?", "Moradabad", ["Aligarh", "Varanasi", "Firozabad"]),
    (106, "Which city is known as 'City of locks'?", "Aligarh", ["Moradabad", "Agra", "Kanpur"]),
    (107, "'Make In India' Project has been launched in which year?", "2014", ["2015", "2016", "2017"]),
    (108, "Who is known as 'Desh-Bandhu'?", "C.R. Das", ["C.F. Andrews", "Subhas Chandra Bose", "B.G. Tilak"]),
    (109, "How many spokes are there in 'Ashoka Chakra'?", "24", ["22", "26", "28"]),
    (110, "Round Revolution is associated with which?", "Potato", ["Onion", "Tomato", "Eggplant"]),
    (111, "'Silao Khaza' is a famous sweet dish of which state?", "Bihar", ["Uttar Pradesh", "West Bengal", "Jharkhand"]),
    (112, "What is the ancient name of sri Lanka?", "Ceylon", ["Burma", "Siam", "Formosa"]),
    (113, "Who was the First Muslim Invader in India?", "Mhd Bin Qasim", ["Mahmud Ghazni", "Muhammad Ghori", "Babur"]),
    (114, "Who had discover 'Vitamin'?", "Funk", ["Pasteur", "Robert Koch", "Alexander Fleming"]),
    (115, "What was the name of first indigenous computer in India?", "Siddharth", ["Param", "Anurag", "Vajra"]),
    (116, "Which is the largest site of Indus valley civilization?", "Rakhigarhi", ["Mohenjodaro", "Harappa", "Lothal"]),
    (117, "What is the hq of 'ICC'?", "Dubai", ["London", "Mumbai", "Melbourne"]),
    (118, "Which country is the highest producer of Gold?", "China", ["Australia", "Russia", "South Africa"]),
    (119, "Wheeler Island is now known as _______.", "Abdul Kalam Island", ["Wheeler Island", "Ross Island", "Havelock Island"]),
    (120, "In which year ISRO was established?", "1969", ["1958", "1962", "1972"]),
    (121, "Kandariya Mahadev Temple is situated in which place?", "Khajuraho", ["Konark", "Puri", "Mount Abu"]),
    (122, "In which state of India, There is maximum forest cover?", "Madhya Pradesh", ["Arunachal Pradesh", "Chhattisgarh", "Odisha"]),
    (123, "What is the shortcut key to open 'Run Prompt'?", "Windows + R", ["Windows + E", "Windows + D", "Windows + L"]),
    (124, "Which glass is used in kitchen Pots?", "Pyrex Glass", ["Soda Glass", "Flint Glass", "Crown Glass"]),
    (125, "Which is the highest silk producing state in India?", "Karnataka", ["Andhra Pradesh", "Tamil Nadu", "West Bengal"]),
    (126, "Ahom kingdom was established in which state of India?", "Assam", ["Manipur", "Tripura", "Meghalaya"]),
    (127, "What is the symptom of Black Fungus?", "Nasal congestion", ["Fever", "Cough", "Skin rash"]),
    (128, "'G-7 Nations' was established in which year?", "1975", ["1985", "1995", "1965"]),
    (129, "Mid Day was started in which year?", "1995", ["1990", "2000", "2005"]),
    (130, "Which state is the highest producer of Saffron?", "Jammu & Kashmir", ["Himachal Pradesh", "Uttarakhand", "Sikkim"]),
    (131, "Kathakali is a famous dance of which state?", "Kerala", ["Tamil Nadu", "Karnataka", "Andhra Pradesh"]),
    (132, "There are how many High Courts in India?", "25", ["21", "24", "28"]),
    (133, "Which Constitutional amendment is known as 'Mini Constitution'?", "42nd", ["44th", "86th", "73rd"]),
    (134, "Who was the founder of Lodi Dynasty?", "Bahlol Lodi", ["Sikandar Lodi", "Ibrahim Lodi", "Khizr Khan"]),
    (135, "Which is the largest fort of India?", "Chittorgarh Fort", ["Mehrangarh Fort", "Red Fort", "Gwalior Fort"]),
    (136, "Who is known as 'shaheed E Azam'?", "Bhagat Singh", ["Chandra Shekhar Azad", "Rajguru", "Sukhdev"]),
    (137, "Who killed General Dyer?", "Udham Singh", ["Bhagat Singh", "Madan Lal Dhingra", "Kartar Singh Sarabha"]),
    (138, "Which river is known as the sorrow of Bengal?", "Damodar", ["Hooghly", "Kosi", "Teesta"]),
    (139, "Who has built peacock throne?", "Shahjahan", ["Akbar", "Jahangir", "Aurangzeb"]),
    (140, "In which year RBI was established?", "1935", ["1947", "1949", "1921"]),
    (141, "Plaster of Paris is made up of ________.", "Gypsum", ["Limestone", "Clay", "Silica"]),
    (142, "Who had discovered 'blood group'?", "Karl Landsteiner", ["William Harvey", "Robert Koch", "Louis Pasteur"]),
    (143, "Which planet is known as 'Evening star'?", "Venus", ["Mars", "Mercury", "Jupiter"]),
    (144, "Tap roots protects plants from whom?", "Worms", ["Insects", "Birds", "Rodents"]),
    (145, "Which gas is found in the Sun Maximum?", "Hydrogen", ["Helium", "Oxygen", "Nitrogen"]),
    (146, "Which city is known as Las Vegas of Asia?", "Macau", ["Hong Kong", "Singapore", "Tokyo"]),
    (147, "Who is the last emperor of Delhi sultanate?", "Ibrahim Lodhi (Ibrahim Lodi)", ["Bahlol Lodi", "Sikandar Lodi", "Daulat Khan Lodi"]),
    (148, "There are how many stars in Indian Railway Logo?", "17", ["15", "16", "18"]),
    (149, "Which state is known as 'Garden of spices'?", "Kerala", ["Karnataka", "Tamil Nadu", "Andhra Pradesh"]),
    (150, "Who was the first president of INC?", "W.C. Banerjee", ["Dadabhai Naoroji", "Badruddin Tyabji", "A.O. Hume"]),
    (151, "Who is the founder of 'Homeopathy'?", "Samuel Hahnemann", ["Hippocrates", "Edward Jenner", "Louis Pasteur"]),
    (152, "'Yakshagaan' is a famous dance of which state?", "Karnataka", ["Kerala", "Andhra Pradesh", "Tamil Nadu"]),
    (153, "Which gas is used to make ripe fruits?", "Ethylene", ["Acetylene", "Methane", "Ethane"]),
    (154, "Which rivers made 'Sundarban Delta'?", "Ganga - Brahmaputra", ["Indus - Ganges", "Krishna - Godavari", "Narmada - Tapti"]),
    (155, "Nobel Award was started in which year?", "1901", ["1911", "1921", "1896"]),
    (156, "Sundarban National Park is situated in which state?", "West Bengal", ["Odisha", "Assam", "Bihar"]),
    (157, "Who was the founder of Fort William College?", "Lord Wellesley", ["Lord Cornwallis", "Warren Hastings", "Lord Dalhousie"]),
    (158, "Hampi is situated in which state?", 'Karnataka (Note: Written as "Humpy" in notes)', ["Andhra Pradesh", "Tamil Nadu", "Kerala"]),
    (159, "Headquarters of Gadar Party is in which city?", "San Francisco", ["New York", "London", "Vancouver"]),
    (160, "What is the ancient name of Allahabad?", "Prayagraj", ["Pataliputra", "Avantika", "Kashi"]),
    (161, "Which country has the largest Border?", "Canada", ["Russia", "China", "USA"]),
    (162, "National Unity Day is celebrated in:", "31st October", ["31st August", "31st December", "31st July"]),
    (163, "Why the colour of Blood is red?", "Haemoglobin", ["Myoglobin", "Chlorophyll", "Hemocyanin"]),
    (164, "In which state, There is a largest number of Railway Tracks?", "Uttar Pradesh", ["Maharashtra", "Rajasthan", "West Bengal"]),
    (165, "What is the source of energy in human body?", "Carbohydrate", ["Protein", "Fat", "Vitamin"]),
    (166, "Who was the first foreigner attacker in India?", "Sikandar (Alexander the Great)", ["Darius", "Cyrus", "Xerxes"]),
    (167, "The one and only Pakistani who awarded with Bharat Ratna:", "Khan Abdul Gaffar Khan", ["Liaquat Ali Khan", "Muhammad Ali Jinnah", "Benazir Bhutto"]),
    (168, "What is the distance measurement unit of ocean?", "Nautical mile", ["Kilometer", "Mile", "Fathom"]),
    (169, "In human, old age become the lack of ______.", "Thymus (Due to degeneration of the thymus gland)", ["Thyroid", "Pituitary", "Adrenal"]),
    (170, "Who is the writer of Malgudie days?", "R.K. Narayan", ["Ruskin Bond", "Mulk Raj Anand", "Raja Rao"]),
    (171, "What is the percentage of Blood in whole human body?", "7%", ["10%", "5%", "12%"]),
    (172, "Which Planet has highest density?", "Earth", ["Mercury", "Venus", "Jupiter"]),
    (173, "There are how many players in gymnastics?", "8", ["6", "7", "9"]),
    (174, "'Straight from the Heart' is a biography of whom?", "Kapil Dev", ["Sunil Gavaskar", "Sachin Tendulkar", "Sourav Ganguly"]),
    (175, "Radha-Mohan Cup is related to which sport?", "Polo", ["Golf", "Tennis", "Hockey"]),
    (176, "What is the national game of New Zealand?", "Rugby", ["Cricket", "Football", "Netball"]),
    (177, "Where is the tomb of saint Kabir?", "Maghar", ["Varanasi", "Ayodhya", "Mathura"]),
    (178, "The one and only active volcano of india is situated in:", "Barren Andaman & Nicobar (Barren Island)", ["Narcondam", "Lakshadweep", "Minicoy"]),
    (179, "Pangong lake is situated in which state?", "Ladakh", ["Jammu & Kashmir", "Himachal Pradesh", "Sikkim"]),
    (180, "World Doctor's day is celebrated on which date?", "2 July", ["1 July", "3 July", "4 July"]),
    (181, "Munda is the main Tribe of which state?", "Jharkhand", ["Chhattisgarh", "Odisha", "Madhya Pradesh"]),
    (182, "What is the idle temperature for rice cultivation?", "20°C - 27°C", ["15°C - 20°C", "25°C - 35°C", "10°C - 15°C"]),
    (183, "Who was designated as a commander in chief in Akbar's court?", "Maan Singh (Man Singh I)", ["Birbal", "Todar Mal", "Tansen"]),
    (184, "Air force day is celebrated on:", "8th October", ["15th January", "4th December", "26th January"]),
    (185, "Which article is known as soul of constitution?", "Article 32", ["Article 19", "Article 21", "Article 14"]),
    (186, "Which gas is used in chips Packet?", "Nitrogen Gas", ["Oxygen Gas", "Carbon Dioxide Gas", "Helium Gas"]),
    (187, "Who is the author of a most famous book 'Life of Pi'?", "Yann Martel", ["Salman Rushdie", "Arundhati Roy", "Kiran Desai"]),
    (188, "One Astronomical Unit is the average distance between:", "Earth and Sun", ["Earth and Moon", "Sun and Pluto", "Sun and Mars"]),
    (189, "Who destroyed 'Nalanda University'?", "Bakhtiyar Khilji", ["Mahmud Ghazni", "Muhammad Ghori", "Alauddin Khilji"]),
    (190, "Which type of waves are used in night vision equipment?", "Infra-red waves", ["Ultraviolet waves", "Microwaves", "Radio waves"]),
    (191, "Butterfly has ______ number of legs.", "Six", ["Four", "Eight", "Ten"]),
    (192, "One barrel of oil is approximately equal to:", "159 litres", ["100 litres", "200 litres", "120 litres"]),
    (193, "Which non-metal exists as a liquid at room temp?", "Bromine", ["Mercury", "Chlorine", "Iodine"]),
    (194, "Which type of glass can cut off UV rays?", "Crook glass (Crookes glass)", ["Pyrex glass", "Soda glass", "Flint glass"]),
    (195, "Who discovered heavy water?", "Harold Clayton Urey", ["Albert Einstein", "Niels Bohr", "Marie Curie"]),
    (196, "When does Heart rest?", "Between two beats", ["During sleep", "Never", "During deep breathing"]),
    (197, "The human hormone insulin is present in:", "Pancreas", ["Thyroid", "Adrenal", "Pituitary"]),
    (198, "'Lona' is related to which game?", "Kabaddi", ["Kho Kho", "Wrestling", "Hockey"]),
    (199, "Tamasha is folk dance of which state?", "Maharashtra", ["Gujarat", "Madhya Pradesh", "Rajasthan"]),
    (200, "Where is 'Chichen Itza' situated?", "Mexico", ["Peru", "Brazil", "Egypt"]),
    (201, "The deepest lake in the world is:", "Baikal lake", ["Superior lake", "Victoria lake", "Caspian Sea"]),
    (202, "Which element is used in the manufacture of safety matches?", "Phosphorous", ["Sulfur", "Carbon", "Sodium"]),
    (203, "Who appoints the members of UPSC?", "President", ["Prime Minister", "Chief Justice", "UPSC Chairman"]),
    (204, "Bharat Ratna was first awarded in:", "1954", ["1950", "1947", "1962"]),
    (205, "Who discovered 'Radioactivity'?", "Henry Becquerel", ["Marie Curie", "Wilhelm Rontgen", "Ernest Rutherford"]),
    (206, "Cinnabar is an ore of which metal?", "Mercury", ["Iron", "Copper", "Lead"]),
    (207, "Which chemical is used for fruit-ripening?", "Acetylene", ["Ethylene", "Methane", "Carbon Dioxide"]),
    (208, "'Giddha' is the famous dance of?", "Punjab", ["Haryana", "Himachal Pradesh", "Rajasthan"]),
    (209, "Who is the first Indian woman to win Miss Universe?", "Sushmita Sen", ["Aishwarya Rai", "Lara Dutta", "Reita Faria"]),
    (210, "What type of disease is Haemophilia?", "Genetic Disease", ["Infectious Disease", "Deficiency Disease", "Viral Disease"]),
    (211, "Kalibanga is located in which state?", "Rajasthan", ["Gujarat", "Punjab", "Haryana"]),
    (212, "Minamata disease is caused by?", "Lead (Note: Handwritten as 'Lead')", ["Lead", "Mercury", "Cadmium", "Arsenic"]),
    (213, "In which field is B.C. Roy award given?", "Medical", ["Sports", "Literature", "Science"]),
    (214, "Layer of a \"capsule\" is made by:", "Starch", ["Gelatin", "Cellulose", "Plastic"]),
    (215, "Twin cities are _______.", "Hyderabad and Sikandarabad", ["Delhi and Noida", "Mumbai and Pune", "Kolkata and Howrah"]),
    (216, "Bandipur Tiger Reserve is situated in which state?", "Karnataka", ["Tamil Nadu", "Kerala", "Andhra Pradesh"]),
    (217, "Thomas Cup is related with:", "Badminton", ["Tennis", "Table Tennis", "Squash"]),
    (218, "'Canis lupus familiaris' is the scientific name of whom?", "Dog", ["Cat", "Wolf", "Fox"]),
    (219, "Bull Fight conducts in which Country?", "Spain", ["Portugal", "Mexico", "France"]),
    (220, "Kailash Temple is situated in:", "Ellora", ["Ajanta", "Elephanta", "Khajuraho"]),
    (221, "Who has the power to impose 'Marshal Law'?", "President", ["Prime Minister", "Chief Justice", "Parliament"]),
    (222, "Narmada River is the life line of which state?", "Madhya Pradesh", ["Gujarat", "Maharashtra", "Rajasthan"]),
    (223, "When was Indian National Airways established?", "1933", ["1923", "1943", "1953"]),
    (224, "Who was the first commander in chief of Indian Army?", "K.M. Kariappa (K.M. Cariappa)", ["Sam Manekshaw", "Bipin Rawat", "Arjan Singh"]),
    (225, "There are how many schedules in Indian constitution?", "12", ["8", "10", "22"]),
    (226, "Which city is known as Boston of India?", "Ahmedabad", ["Mumbai", "Kolkata", "Chennai"]),
    (227, "Which city is known as 'City of Roses'?", "Chandigarh", ["Jaipur", "Srinagar", "Lucknow"]),
    (228, "Which is the first Oscar award winning Indian movie?", "Gandhi (Bhanu Athaiya won Best Costume Design for the movie 'Gandhi' in 1983)", ["Mother India", "Salaam Bombay", "Lagaan"]),
    (229, "Who gave Black hole concept in India?", "S. Chandra Shekhar (Subrahmanyan Chandrasekhar)", ["C.V. Raman", "Homi Bhabha", "Vikram Sarabhai"]),
    (230, "What is the currency of Norway?", "Krone", ["Euro", "Dollar", "Pound"]),
    (231, "Which is the twin planet of Earth?", "Venus", ["Mars", "Mercury", "Uranus"]),
    (232, "Which state is known as sleeping state of India?", "Madhya Pradesh (Due to high soy production, often called 'Soy State' or sleeping state)", ["Uttar Pradesh", "Rajasthan", "Maharashtra"]),
    (233, "Bridge of Adam is between:", "India and Srilanka", ["India and Maldives", "India and Bangladesh", "India and Myanmar"]),
    (234, "Which is the first english translated movie in India?", "Noorjahan", ["Raja Harishchandra", "Alam Ara", "Devdas"]),
    (235, "Who is the inventor of WWW?", "Tim Berners Lee", ["Bill Gates", "Steve Jobs", "Vint Cerf"]),
    (236, "Who is known as the king of justice?", "Jahanger (Jahangir)", ["Akbar", "Shah Jahan", "Aurangzeb"]),
    (237, "'Natraj Temple' is situated in:", "Chidambaram", ["Madurai", "Tanjore", "Rameshwaram"]),
    (238, "Who is the chairman of Rajya Sabha?", "Vice-President", ["Prime Minister", "President", "Speaker of Lok Sabha"]),
    (239, "pH value of urine:", "6.0", ["7.0", "5.0", "8.0"]),
    (240, "Which State is the highest producer of Eggs?", "Andhra Pradesh", ["Tamil Nadu", "Karnataka", "Punjab"]),
    (241, "Who is the inventor of diesel engine?", "James Watt (Note: Written as 'James Watt')", ["James Watt", "Rudolf Diesel", "Thomas Edison", "George Stephenson"]),
    (242, "In which year Taj Mahal construction has been completed?", "1653 AD", ["1648 AD", "1658 AD", "1660 AD"]),
    (243, "AIDS day celebrated in:", "1st December", ["1st November", "1st October", "1st September"]),
    (244, "Which is the highest lake of the world?", "Titicaca", ["Baikal", "Victoria", "Tanganyika"]),
    (245, "What is the fuel of future?", "Hydrogen", ["Helium", "Nitrogen", "Methane"]),
    (246, "Which country is known as 'land of Thunder Bolt'?", "Bhutan", ["Nepal", "Tibet", "Myanmar"]),
    (247, "Who is first lady IAS officer?", "Anna George (Anna Rajam Malhotra)", ["Kiran Bedi", "Arundhati Roy", "Sarojini Naidu"]),
    (248, "Which state is the highest producer of coffee in India?", "Karnataka", ["Kerala", "Tamil Nadu", "Andhra Pradesh"]),
    (249, "Who abolished slavery system in India?", "Akbar", ["Babur", "Humayun", "Shah Jahan"]),
    (250, "There are how many judges in supreme court?", "34", ["30", "31", "35"]),
    (251, "World Tourism day:", "27 September", ["27 October", "27 November", "27 August"]),
    (252, "Which article belongs to 'Impeachment of President'?", "Article 61", ["Article 52", "Article 72", "Article 356"]),
    (253, "In which year Mumbai High Court was established?", "1862", ["1857", "1872", "1882"]),
    (254, "Which is the largest mosque in India?", "Jama Masjid", ["Mecca Masjid", "Taj-ul-Masajid", "Hazratbal"]),
    (255, "Who was the first Indian to be elected as member of British Parliament?", "D.B. Naoroji (Dadabhai Naoroji)", ["W.C. Banerjee", "Gopal Krishna Gokhale", "Dinshaw Wacha"]),
    (256, "Which state is the highest producer of Mango?", "Uttar Pradesh", ["Andhra Pradesh", "Maharashtra", "Bihar"]),
    (257, "Which city is the main industrial area of diamond cutting?", "Ahmedabad (Note: Written as 'Ahmedabad')", ["Surat", "Ahmedabad", "Mumbai", "Jaipur"]),
    (258, "Who established 'Nalanda University'?", "Kumar Gupta (Kumaragupta I)", ["Chandragupta II", "Samudragupta", "Skandagupta"]),
    (259, "Which state is the highest producer of Guava?", "Jharkhand", ["Bihar", "Uttar Pradesh", "West Bengal"]),
    (260, "Which is the smallest ocean in the world?", "Arctic Ocean", ["Indian Ocean", "Southern Ocean", "Pacific Ocean"]),
    (261, "'Tocopherol' is the chemical name of:", "Vitamin E", ["Vitamin A", "Vitamin C", "Vitamin K"]),
    (262, "Which state is the highest producer of peanuts?", "Gujarat", ["Rajasthan", "Maharashtra", "Andhra Pradesh"]),
    (263, "Which state is the highest producer of onion?", "Maharashtra", ["Gujarat", "Madhya Pradesh", "Uttar Pradesh"]),
    (264, "When oral polio vaccine came into use?", "1961", ["1955", "1965", "1970"]),
    (265, "What is the length of Cricket pitch?", "66 feet (22 yards)", ["60 feet", "70 feet", "75 feet"]),
    (266, "Which Country is known as Bowl of sugar?", "Cuba", ["Brazil", "India", "USA"]),
    (267, "Which is the smallest river in the world?", "Roe river", ["Amazon river", "Nile river", "Congo river"]),
    (268, "Which is the largest district of India?", "Kutch", ["Leh", "Jaisalmer", "Barmer"]),
    (269, "Which is the country of snakes?", "Brazil", ["India", "Australia", "South Africa"]),
    (270, "Which city is known as Garden of India?", "Chandigarh (Note: Written as 'Chandigarh')", ["Chandigarh", "Bangalore", "Pune", "Mysore"]),
    (271, "Which city is known as 'city of glutton'?", "Indore", ["Bhopal", "Ujjain", "Gwalior"]),
    (272, "Which is the smallest district of India?", "Mahe", ["Diu", "Lakshadweep", "Yanam"]),
    (273, "Borlaug Award is related to which field?", "Agriculture", ["Science", "Medicine", "Journalism"]),
    (274, "There are how many bones in human head?", "8 bones (Note: Written as '8 bones')", ["8 bones", "14 bones", "22 bones", "20 bones"]),
    (275, "Which city is known as capital of cotton clothes?", "Mumbai", ["Surat", "Ahmedabad", "Coimbatore"]),
    (276, "Wimbledon Trophy is related to which sport?", "Lawn Tennis", ["Badminton", "Squash", "Table Tennis"]),
    (277, "Which is the longest indoor stadium of India?", "Indira Gandhi Stadium (Indira Gandhi Indoor Arena, Delhi)", ["Netaji Indoor Stadium", "Salt Lake Stadium", "Talkatora Stadium"]),
    (278, "What is the currency of 'slovakia'?", "Euro", ["Koruna", "Krone", "Dollar"]),
    (279, "The official government documents of India is known as:", "White Paper", ["Blue Book", "Green Paper", "Yellow Book"]),
    (280, "Kuchipudi dance belongs to which state?", "Andhra Pradesh", ["Tamil Nadu", "Kerala", "Karnataka"]),
    (281, "What is the previous name of Lucknow?", "Lakhnauti (Note: Written as 'Lakhnauti')", ["Lakhnauti", "Lakshmanpur", "Awadh", "Lucknow"]),
    (282, "Which state is the highest producer of silk?", "Karnataka", ["Andhra Pradesh", "West Bengal", "Tamil Nadu"]),
    (283, "Ryder cup is related to which sport?", "Golf", ["Tennis", "Cricket", "Polo"]),
    (284, "What protocol is used in data transfer?", "FTP (File Transfer Protocol)", ["HTTP", "SMTP", "TCP"]),
    (285, "Who is the writer of Mahabharata?", "Ved Vyas", ["Valmiki", "Kalidas", "Tulsidas"]),
    (286, "Deodhar Trophy is related to which sport?", "Cricket", ["Football", "Hockey", "Tennis"]),
    (287, "Who invented x-rays?", "Conrad Rontgen (Wilhelm Conrad Röntgen)", ["Marie Curie", "Thomas Edison", "Alexander Fleming"]),
    (288, "Zojila pass is in which state?", "Ladakh", ["Jammu & Kashmir", "Himachal Pradesh", "Uttarakhand"]),
    (289, "Who invented \"Telegraph\"?", "Samuel Morse", ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi"]),
    (290, "Rajiv Gandhi died in which state?", "Tamil Nadu", ["Andhra Pradesh", "Karnataka", "Kerala"]),
    (291, "What is the capital of Maldives?", "Male", ["Colombo", "Dhaka", "Kathmandu"]),
    (292, "What is the currency of Myanmar?", "Kyat", ["Rupee", "Baht", "Taka"]),
    (293, "What is the finance capital of India?", "Mumbai", ["Delhi", "Kolkata", "Chennai"]),
    (294, "Who is known as the father of 'Economy'?", "Adam Smith", ["Karl Marx", "Alfred Marshall", "John Keynes"]),
    (295, "Who is the founder of Chola Dynasty?", "Vijayalaya", ["Rajaraja I", "Rajendra I", "Aditya I"]),
    (296, "What is the national language of Bangladesh?", "Bengali", ["Urdu", "Hindi", "English"]),
    (297, "What is used in Electric Heater?", "Nichrome", ["Copper", "Iron", "Tungsten"])
]

def generate_options(correct, distractors):
    # Returns [A, B, C, D] options and the letter ('A', 'B', 'C', or 'D')
    opts = [correct] + list(distractors)
    # Sort them alphabetically to have a deterministic order, or just random
    # Let's use random with a fixed seed so it's deterministic but mixed
    r = random.Random(correct)
    r.shuffle(opts)
    
    letter_map = {0: 'A', 1: 'B', 2: 'C', 3: 'D'}
    correct_idx = opts.index(correct)
    return opts, letter_map[correct_idx]

def main():
    print("Generating files...")
    
    # 1. Write NewData.md
    with open("NewData.md", "w", encoding="utf-8") as f:
        f.write("Lucent's Book Important Questions (Quiz Format)\n\n")
        for q_id, question, correct, distractors in RAW_DATA:
            opts, correct_letter = generate_options(correct, distractors)
            f.write(f"{q_id}. {question}\n")
            f.write(f"   A. {opts[0]}\n")
            f.write(f"   B. {opts[1]}\n")
            f.write(f"   C. {opts[2]}\n")
            f.write(f"   D. {opts[3]}\n")
            f.write(f"   Ans: {correct}\n\n")
            
    # 2. Write csv/lucent.csv
    # Topic,Subtopic,Pattern,Question,A,B,C,D,Answer,Source
    with open("csv/lucent.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Topic", "Subtopic", "Pattern", "Question", "A", "B", "C", "D", "Answer", "Source"])
        for q_id, question, correct, distractors in RAW_DATA:
            opts, correct_letter = generate_options(correct, distractors)
            # Find subtopic based on keyword matching
            subtopic = "General"
            q_lower = question.lower()
            if "river" in q_lower or "lake" in q_lower or "ocean" in q_lower or "state" in q_lower or "capital" in q_lower or "border" in q_lower or "planet" in q_lower or "solar" in q_lower or "valley" in q_lower or "island" in q_lower:
                subtopic = "Geography"
            elif "king" in q_lower or "emperor" in q_lower or "dynasty" in q_lower or "established" in q_lower or "founded" in q_lower or "revolt" in q_lower or "tragedy" in q_lower or "first female ruler" in q_lower or "invented" in q_lower or "historical" in q_lower:
                subtopic = "History"
            elif "article" in q_lower or "constitution" in q_lower or "amendment" in q_lower or "president" in q_lower or "governor" in q_lower or "supreme commander" in q_lower or "high court" in q_lower or "judges" in q_lower:
                subtopic = "Polity"
            elif "cup" in q_lower or "trophy" in q_lower or "sport" in q_lower or "game" in q_lower or "player" in q_lower or "olympic" in q_lower or "cricket" in q_lower or "gymnastic" in q_lower:
                subtopic = "Sports"
            elif "vitamin" in q_lower or "disease" in q_lower or "organ" in q_lower or "gland" in q_lower or "scientific name" in q_lower or "blood" in q_lower or "glass" in q_lower or "gas" in q_lower or "chemical" in q_lower or "metal" in q_lower or "bone" in q_lower:
                subtopic = "Science"
            elif "computer" in q_lower or "shortcut" in q_lower or "program" in q_lower or "www" in q_lower or "telegraph" in q_lower:
                subtopic = "Computer"
                
            writer.writerow([
                "GK",
                subtopic,
                "Standard MCQ",
                question,
                opts[0],
                opts[1],
                opts[2],
                opts[3],
                correct,
                "Lucent"
            ])
            
    print("Files created successfully.")

if __name__ == "__main__":
    main()
